name: "ci"

on:
  push:
    branches: 
      - '*'
    tags-ignore:
      - '*'
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: verify go version
        run: go version
      - name: Test
        run: go test -v ./...
     
